shared:
    image: node:6

jobs:
    main:
        steps:
            - install: npm install screwdriver-template-main
            - rename:  mv sd-template-android.yaml sd-template.yaml
            - publish: node ./node_modules/.bin/template-publish
