shared:
    image: node:6

jobs:
    template:
        requires: [~pr, ~commit]
        steps:
            - prep: npm install screwdriver-template-main
            - prepfile: mv sd-template-publish.yaml sd-template.yaml
            - publish: node ./node_modules/.bin/template-publish
    android:
        requires: [template]
        template: screwdriver/template-publish
        steps:
            - preinstall: mv sd-template-android.yaml sd-template.yaml
